version: '3.8'
services:
  springboot-customer:
    build:
      context: client-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      cont-db:
        condition: service_healthy
    environment:
      WAIT_HOSTS: cont-db:5432

  springboot-bank-accounts:
    build:
      context: bank-account-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      cont-db:
        condition: service_healthy
    environment:
      WAIT_HOSTS: cont-db:5432

  cont-db:
    container_name: cont-db
    build:
      context: postgres-db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U adminbankservices"]
       interval: 10s
       retries: 5
      
networks:
  my-network:

volumes:
  postgres-data:
     driver: local

